version: '3.8'
services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Teste123
      POSTGRES_DB: mydb
    volumes:
      - postgres-data:/var/lib/postgres/data

volumes:
 postgres-data: